security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8766/eureka
